// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/evlilik": {
    params: {};
  };
  "/hakkinda": {
    params: {};
  };
  "/iletisim": {
    params: {};
  };
  "/seyahat": {
    params: {};
  };
  "/youtube": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/evlilik" | "/hakkinda" | "/iletisim" | "/seyahat" | "/youtube" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./admin/page.jsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./evlilik/page.jsx": {
    id: "evlilik/page";
    page: "/evlilik";
  };
  "./hakkinda/page.jsx": {
    id: "hakkinda/page";
    page: "/hakkinda";
  };
  "./iletisim/page.jsx": {
    id: "iletisim/page";
    page: "/iletisim";
  };
  "./seyahat/page.jsx": {
    id: "seyahat/page";
    page: "/seyahat";
  };
  "./youtube/page.jsx": {
    id: "youtube/page";
    page: "/youtube";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "admin/page": typeof import("./src/app/./admin/page.jsx");
  "evlilik/page": typeof import("./src/app/./evlilik/page.jsx");
  "hakkinda/page": typeof import("./src/app/./hakkinda/page.jsx");
  "iletisim/page": typeof import("./src/app/./iletisim/page.jsx");
  "seyahat/page": typeof import("./src/app/./seyahat/page.jsx");
  "youtube/page": typeof import("./src/app/./youtube/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};